# -*- coding: utf-8 -*-
"""qES.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cx07gr_yq4YH2xB2hSxWuNME1YPwf30t
"""

import numpy as np

def ES(losses, alpha=None, VaR=None):

    if VaR is None:

        VaR = np.percentile(losses, 100 * alpha)

    es_value = np.mean(losses[losses > VaR])
    return es_value

#ES Test

u = np.random.uniform(0, 100, 100000)

es_alpha = ES(losses=u, alpha=0.8)

np.round(es_alpha, 0) == 90

es_var = ES(losses=u, VaR=80)

np.round(es_var, 0) == 90

