# -*- coding: utf-8 -*-
"""qGetReturns.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D4n5jMMaDfhqyinFzXdU6o9doOuFFSjy
"""

import pandas as pd
import yfinance as yf

def YahooData2returns(data):

    if isinstance(data, pd.DataFrame):
        prices = data['Adj Close']
    else:
        prices = data

    returns = prices.pct_change()

    returns = returns.dropna()

    return returns

def get_stock_data(ticker, start=None, end=None):

    data = yf.download(ticker, start=start, end=end)

    adj_close = data['Adj Close']
    return adj_close

def get_returns(ticker, start=None, end=None):

    adj_close = get_stock_data(ticker, start=start, end=end)

    returns = YahooData2returns(adj_close)
    return returns

def test_YahooData2returns():

    sample_data = pd.DataFrame({'Adj Close': [100, 110, 121]})

    expected_returns = [0.10, 0.10]

    computed_returns = YahooData2returns(sample_data)

    computed_list = computed_returns.tolist()

    for expected, computed in zip(expected_returns, computed_list):
        assert abs(computed - expected) < 1e-6, f"Return {computed} differs from expected {expected}"
    print("test_YahooData2returns passed.")

if __name__ == "__main__":
    test_YahooData2returns()



