# -*- coding: utf-8 -*-
"""qGetReturns.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D4n5jMMaDfhqyinFzXdU6o9doOuFFSjy
"""

import yfinance as yf
import numpy as np
import pandas as pd

def YahooData2returns(YahooData):

    if 'Adj Close' not in YahooData.columns:
        raise ValueError("The dataset is missing the 'Adj Close' column. Check auto_adjust=False.")

    pricevec = YahooData['Adj Close'].values
    returns = pricevec[1:] / pricevec[:-1] - 1
    return returns

def get_stock_data(symbol, start=None, end=None):

    data = yf.download(symbol, start=start, end=end, auto_adjust=False)
    return data

symbol = 'GS'
stock_data = get_stock_data(symbol, start='2023-01-01', end='2024-01-01')

if 'Adj Close' in stock_data.columns:
    returns = YahooData2returns(stock_data)
    print(f"Lagged returns for {symbol}:")
    print(returns)
else:
    print("Error: 'Adj Close' column is missing. Ensure Yahoo Finance data is correctly retrieved.")

